import { getEnv } from '../utils/get-env'

const appConfig = () => ({
    NODE_ENV: getEnv('NODE_ENV', 'development'),
    PORT: getEnv('PORT', '5000'),
    BASE_PATH: getEnv('BASE_PATH', '/api'),
    MONGO_URI: getEnv('MONGO_URI', ''),
    SESSION_SECRET: getEnv('SESSION_SECRET'),
    SESSION_EXPIRES_IN: getEnv('SESSION_EXPIRES_IN'),
    GOOGLE_CLIENT_ID: getEnv('GOOGLE_CLIENT_ID'),
    GOOGLE_CLIENT_SECRET: getEnv('GOOGLE_CLIENT_SECRET'),
    GOOGLE_CALLBACK_URL: getEnv('GOOGLE_CALLBACK_URL'),
    FRONTEND_ORIGIN: getEnv('FRONTEND_ORIGIN', 'localhost'),
    FRONTEND_GOOGLE_CALLBACK_URL: getEnv('FRONTEND_GOOGLE_CALLBACK_URL'),
    JWT_SECRET: getEnv('JWT_SECRET'),
    JWT_EXPIRES_IN: getEnv('JWT_EXPIRES_IN', '15m'),
    REFRESH_JWT_SECRET: getEnv('REFRESH_JWT_SECRET'),
    REFRESH_JWT_EXPIRES_IN: getEnv('REFRESH_JWT_EXPIRES_IN', '30d'),
    RESEND_API_KEY: getEnv('RESEND_API_KEY'),
    MAILER_SENDER: getEnv('MAILER_SENDER'),

    CLOUDINARY_CLOUD_NAME: getEnv('CLOUDINARY_CLOUD_NAME'),
    CLOUDINARY_API_KEY: getEnv('CLOUDINARY_API_KEY'),
    CLOUDINARY_API_SECRET: getEnv('CLOUDINARY_API_SECRET'),
})

export const config = appConfig()
